// Summarises Lighthouse JSON reports as a Markdown table.
// Usage: node scripts/lh-summary.mjs <reportsDir> [--write]   (--write saves SUMMARY.md next to the reports)
import fs from "node:fs";
import path from "node:path";

const [dir, flag] = process.argv.slice(2);
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".report.json")).sort();
const pct = (c) => (c?.score == null ? "–" : String(Math.round(c.score * 100)));
const rows = [];
for (const f of files) {
  const r = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
  const a = r.audits, c = r.categories;
  const name = f.replace(".report.json", "");
  const [preset, ...rest] = name.split("-");
  rows.push({
    preset, page: rest.join("-"), url: new URL(r.finalDisplayedUrl ?? r.finalUrl).pathname,
    perf: pct(c.performance), a11y: pct(c.accessibility), bp: pct(c["best-practices"]), seo: pct(c.seo),
    fcp: a["first-contentful-paint"]?.displayValue ?? "–", lcp: a["largest-contentful-paint"]?.displayValue ?? "–",
    tbt: a["total-blocking-time"]?.displayValue ?? "–", cls: a["cumulative-layout-shift"]?.displayValue ?? "–",
    js: Math.round((a["resource-summary"]?.details?.items?.find((i) => i.resourceType === "script")?.transferSize ?? a["network-requests"]?.details?.items?.filter((i) => i.resourceType === "Script").reduce((s, i) => s + (i.transferSize ?? 0), 0) ?? 0) / 1024),
    weight: Math.round((a["total-byte-weight"]?.numericValue ?? 0) / 1024),
  });
}
const out = [];
for (const preset of ["desktop", "mobile"]) {
  const set = rows.filter((r) => r.preset === preset);
  if (!set.length) continue;
  out.push(`### ${preset === "desktop" ? "Desktop" : "Mobile (Moto G Power emulation, slow 4G, 4× CPU slowdown)"}`, "");
  out.push("| Page | Perf | A11y | Best pr. | SEO | FCP | LCP | TBT | CLS | JS transferred | Page weight |", "|---|---|---|---|---|---|---|---|---|---|---|");
  for (const r of set) out.push(`| \`${r.url}\` | ${r.perf} | ${r.a11y} | ${r.bp} | ${r.seo} | ${r.fcp} | ${r.lcp} | ${r.tbt} | ${r.cls} | ${r.js} KB | ${r.weight} KB |`);
  out.push("");
}
const md = out.join("\n").replace(/ /g, " ");
console.log(md);
if (flag === "--write") fs.writeFileSync(path.join(dir, "SUMMARY.md"), `# Lighthouse results\n\nGenerated by \`site/scripts/lh-summary.mjs\` from the reports in this folder.\n\n${md}`);
